-- 自動產生，請勿手動編輯。來源：scripts/seedData.js（執行 node scripts/generate-seed-sql.js 重新產生）
DELETE FROM order_menu_items;
DELETE FROM orders;
DELETE FROM monthly_menu_items;
DELETE FROM dish_ingredients;
DELETE FROM dishes;

INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (1, '白飯', '主食', 0, '素', '煮', '白', 0, 0, 20, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (1, '白米', 600, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (2, '炒麵', '主食', 0, '素', '炒', '黃', 0, 0, 35, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (2, '油麵', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (2, '高麗菜', 150, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (2, '紅蘿蔔絲', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (3, '炒米粉', '主食', 0, '素', '炒', '白', 0, 0, 35, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (3, '米粉', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (3, '高麗菜', 150, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (3, '香菇絲', 30, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (4, '筒仔米糕', '主食', 1, '豬', '蒸', '褐', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (4, '長糯米', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (4, '滷肉燥', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (4, '香菇', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (5, '芋頭米粉', '主食', 0, '素', '炒', '褐', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (5, '米粉', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (5, '芋頭', 150, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (6, '蛋炒飯', '主食', 0, '蛋', '炒', '黃', 0, 0, 35, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (6, '白飯', 600, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (6, '雞蛋', 3, '顆');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (7, '油飯', '主食', 1, '豬', '蒸', '褐', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (7, '長糯米', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (7, '豬肉絲', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (7, '香菇', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (8, '什錦炒飯', '主食', 0, '素', '炒', '黃', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (8, '白飯', 600, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (8, '玉米粒', 80, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (8, '青豆', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (9, '紅燒獅子頭', '主菜', 1, '豬', '滷', '褐', 0, 0, 90, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (9, '豬絞肉', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (9, '大白菜', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (9, '荸薺', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (10, '糖醋排骨', '主菜', 1, '豬', '炸', '紅', 0, 0, 95, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (10, '小排骨', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (10, '鳳梨片', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (10, '青椒', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (11, '客家小炒', '主菜', 1, '豬', '炒', '褐', 0, 0, 85, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (11, '五花肉', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (11, '魷魚乾', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (11, '豆干', 150, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (11, '芹菜', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (12, '香煎雞腿排', '主菜', 0, '雞', '煎', '褐', 0, 0, 100, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (12, '去骨雞腿', 600, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (13, '蔥爆牛肉', '主菜', 0, '牛', '炒', '褐', 0, 0, 120, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (13, '牛肉片', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (13, '青蔥', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (13, '洋蔥', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (14, '樹子蒸鱈魚', '主菜', 0, '魚', '蒸', '白', 0, 0, 150, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (14, '鱈魚', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (14, '破布子', 30, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (14, '薑絲', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (15, '塔香三杯雞', '主菜', 0, '雞', '炒', '褐', 1, 0, 100, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (15, '雞腿肉', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (15, '九層塔', 30, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (15, '老薑', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (16, '避風塘蝦', '主菜', 0, '海鮮', '炸', '黃', 1, 0, 160, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (16, '白蝦', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (16, '蒜酥', 60, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (16, '辣椒末', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (17, '蒜泥蒸魚', '主菜', 0, '魚', '蒸', '白', 0, 0, 120, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (17, '鱸魚', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (17, '蒜泥', 40, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (18, '京都排骨', '主菜', 1, '豬', '炸', '紅', 0, 0, 90, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (18, '大排', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (18, '洋蔥', 60, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (19, '東坡肉', '主菜', 1, '豬', '滷', '褐', 0, 1, 110, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (19, '五花肉塊', 500, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (20, '左宗棠雞', '主菜', 0, '雞', '炸', '紅', 1, 0, 110, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (20, '雞胸肉', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (20, '乾辣椒', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (21, '宮保雞丁', '主菜', 0, '雞', '炒', '紅', 1, 0, 95, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (21, '雞胸肉', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (21, '花生', 80, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (21, '乾辣椒', 15, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (22, '蜜汁叉燒', '主菜', 1, '豬', '烤', '紅', 0, 0, 100, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (22, '梅花肉', 500, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (23, '檸檬蒸魚', '主菜', 0, '魚', '蒸', '白', 0, 0, 130, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (23, '龍膽石斑', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (23, '檸檬', 2, '顆');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (24, '紅燒牛腩', '主菜', 0, '牛', '滷', '褐', 0, 1, 140, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (24, '牛腩', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (24, '紅蘿蔔', 100, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (25, '黑胡椒牛柳', '主菜', 0, '牛', '炒', '褐', 0, 0, 130, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (25, '牛柳', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (25, '洋蔥', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (26, '塔香海鮮', '主菜', 0, '海鮮', '炒', '黃', 1, 0, 150, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (26, '綜合海鮮', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (26, '九層塔', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (27, '白斬雞', '主菜', 0, '雞', '煮', '白', 0, 0, 100, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (27, '土雞腿', 600, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (28, '燒酒雞', '主菜', 0, '雞', '滷', '褐', 0, 0, 110, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (28, '雞腿肉', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (28, '米酒', 300, 'ml');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (29, '蒜香排骨酥', '主菜', 1, '豬', '炸', '褐', 0, 0, 95, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (29, '小排骨', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (29, '蒜末', 40, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (30, '沙茶羊肉', '主菜', 0, '羊', '炒', '褐', 1, 0, 150, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (30, '羊肉片', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (30, '沙茶醬', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (31, 'XO醬炒海鮮', '主菜', 0, '海鮮', '炒', '紅', 1, 0, 160, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (31, '綜合海鮮', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (31, 'XO醬', 40, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (32, '蒸烤鴨腿', '主菜', 0, '其他', '烤', '褐', 0, 0, 140, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (32, '鴨腿', 500, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (33, '檸檬鮭魚', '主菜', 0, '魚', '煎', '橙', 0, 0, 140, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (33, '鮭魚', 450, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (33, '檸檬', 1, '顆');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (34, '蔥燒鯽魚', '主菜', 0, '魚', '煎', '褐', 0, 0, 110, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (34, '鯽魚', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (34, '青蔥', 60, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (35, '塔香烘蛋', '主菜', 0, '蛋', '煎', '黃', 0, 0, 70, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (35, '雞蛋', 6, '顆');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (35, '九層塔', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (36, '蒜燒中卷', '主菜', 0, '海鮮', '炒', '白', 0, 0, 120, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (36, '中卷', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (36, '蒜苗', 60, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (37, '紅麴排骨', '主菜', 1, '豬', '炸', '紅', 0, 0, 95, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (37, '小排骨', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (37, '紅麴醬', 40, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (38, '蜜汁烤雞腿', '主菜', 0, '雞', '烤', '褐', 0, 0, 110, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (38, '雞腿', 600, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (39, '塔香牛肉', '主菜', 0, '牛', '炒', '褐', 1, 0, 140, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (39, '牛肉片', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (39, '九層塔', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (40, '荷葉粉蒸肉', '主菜', 1, '豬', '蒸', '褐', 0, 1, 100, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (40, '五花肉片', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (40, '蒸肉粉', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (41, '檸檬雞排', '主菜', 0, '雞', '炸', '黃', 0, 0, 100, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (41, '雞胸肉', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (41, '檸檬', 2, '顆');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (42, '麻油雞', '主菜', 0, '雞', '煮', '褐', 0, 1, 110, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (42, '雞腿肉', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (42, '麻油', 50, 'ml');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (42, '老薑', 40, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (43, '蒜蓉蒸蝦', '主菜', 0, '海鮮', '蒸', '白', 0, 0, 150, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (43, '草蝦', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (43, '蒜蓉', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (44, '螞蟻上樹', '副菜', 1, '豬', '炒', '紅', 1, 0, 60, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (44, '冬粉', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (44, '豬絞肉', 150, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (45, '麻婆豆腐', '副菜', 1, '豬', '煮', '紅', 1, 0, 55, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (45, '嫩豆腐', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (45, '豬絞肉', 100, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (46, '滷豆干海帶', '副菜', 0, '素', '滷', '褐', 0, 1, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (46, '豆干', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (46, '海帶', 200, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (47, '涼拌小黃瓜', '副菜', 0, '素', '涼拌', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (47, '小黃瓜', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (47, '蒜末', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (48, '蒜泥白肉', '副菜', 1, '豬', '煮', '白', 0, 0, 70, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (48, '五花肉片', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (48, '蒜泥', 30, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (49, '蔭豉蚵仔', '副菜', 0, '海鮮', '煮', '黑', 0, 0, 90, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (49, '鮮蚵', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (49, '豆豉', 20, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (49, '薑絲', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (50, '涼拌木耳', '副菜', 0, '素', '涼拌', '黑', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (50, '黑木耳', 250, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (51, '客家封肉', '副菜', 1, '豬', '滷', '褐', 0, 1, 85, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (51, '五花肉塊', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (51, '梅乾菜', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (52, '塔香豆腐煲', '副菜', 0, '素', '滷', '褐', 0, 0, 55, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (52, '板豆腐', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (52, '九層塔', 15, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (53, '開陽白菜', '副菜', 0, '素', '煮', '白', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (53, '大白菜', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (53, '蝦米', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (54, '涼拌豆芽', '副菜', 0, '素', '涼拌', '白', 0, 0, 35, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (54, '綠豆芽', 350, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (55, '紅燒杏鮑菇', '副菜', 0, '素', '滷', '褐', 0, 0, 50, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (55, '杏鮑菇', 300, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (56, '皮蛋豆腐', '副菜', 0, '蛋', '生食', '黑', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (56, '皮蛋', 4, '顆');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (56, '嫩豆腐', 300, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (57, '涼拌海帶芽', '副菜', 0, '素', '涼拌', '綠', 0, 0, 35, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (57, '海帶芽', 200, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (58, '紹興醉雞', '副菜', 0, '雞', '煮', '白', 0, 0, 80, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (58, '去骨雞腿', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (58, '紹興酒', 100, 'ml');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (59, '五香滷牛腱', '副菜', 0, '牛', '滷', '褐', 0, 0, 90, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (59, '牛腱', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (60, '涼拌花枝', '副菜', 0, '海鮮', '涼拌', '白', 0, 0, 70, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (60, '花枝', 300, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (61, '客家炒肉絲', '副菜', 1, '豬', '炒', '褐', 0, 0, 60, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (61, '豬肉絲', 250, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (61, '豆干絲', 100, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (62, '塔香茭白筍', '副菜', 0, '素', '炒', '白', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (62, '茭白筍', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (62, '九層塔', 15, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (63, '破布子蒸肉餅', '副菜', 1, '豬', '蒸', '褐', 0, 1, 65, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (63, '豬絞肉', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (63, '破布子', 30, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (64, '涼拌娃娃菜', '副菜', 0, '素', '涼拌', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (64, '娃娃菜', 300, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (65, '蒜香四季豆', '副菜', 0, '素', '炒', '綠', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (65, '四季豆', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (65, '蒜末', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (66, '客家小魚乾', '副菜', 0, '海鮮', '炒', '黑', 1, 0, 55, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (66, '小魚乾', 150, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (66, '花生', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (67, '塔香皮蛋', '副菜', 0, '蛋', '炒', '黑', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (67, '皮蛋', 4, '顆');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (67, '九層塔', 15, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (68, '涼拌牛腱', '副菜', 0, '牛', '涼拌', '褐', 0, 0, 85, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (68, '牛腱', 350, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (69, '塔香素肚', '副菜', 0, '素', '炒', '黃', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (69, '素肚', 250, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (69, '九層塔', 15, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (70, '清炒高麗菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (70, '高麗菜', 500, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (71, '炒地瓜葉', '時蔬', 0, '素', '炒', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (71, '地瓜葉', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (72, '蒜炒A菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (72, 'A菜', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (73, '香菇燴時蔬', '時蔬', 0, '素', '煮', '綠', 0, 1, 50, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (73, '綜合時蔬', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (73, '乾香菇', 30, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (74, '塔香茄子', '時蔬', 0, '素', '炒', '紫', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (74, '茄子', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (74, '九層塔', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (75, '炒青花菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (75, '青花菜', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (76, '開陽高麗菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (76, '高麗菜', 450, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (76, '蝦米', 15, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (77, '蒜炒山蘇', '時蔬', 0, '素', '炒', '綠', 0, 0, 50, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (77, '山蘇', 350, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (78, '皇宮菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (78, '皇宮菜', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (79, '炒龍鬚菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 50, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (79, '龍鬚菜', 350, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (80, '蒜炒油菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (80, '油菜', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (81, '清炒絲瓜', '時蔬', 0, '素', '炒', '綠', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (81, '絲瓜', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (82, '炒山藥', '時蔬', 0, '素', '炒', '白', 0, 0, 50, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (82, '山藥', 350, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (83, '涼拌秋葵', '時蔬', 0, '素', '涼拌', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (83, '秋葵', 300, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (84, '塔香四季豆', '時蔬', 0, '素', '炒', '綠', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (84, '四季豆', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (84, '九層塔', 15, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (85, '清炒白花椰', '時蔬', 0, '素', '炒', '白', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (85, '白花椰菜', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (86, '蒜香蘆筍', '時蔬', 0, '素', '炒', '綠', 0, 0, 55, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (86, '蘆筍', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (86, '蒜末', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (87, '炒紅鳳菜', '時蔬', 0, '素', '炒', '紅', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (87, '紅鳳菜', 350, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (88, '蒜炒莧菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (88, '莧菜', 350, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (89, '蒜炒空心菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (89, '空心菜', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (90, '五味小卷拼盤', '配菜', 0, '海鮮', '涼拌', '白', 0, 0, 100, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (90, '小卷', 300, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (91, '滷味拼盤', '配菜', 1, '豬', '滷', '褐', 0, 0, 90, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (91, '豬耳朵', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (91, '豆干', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (91, '海帶', 100, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (92, '涼拌三絲', '配菜', 0, '素', '涼拌', '白', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (92, '干絲', 150, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (92, '紅蘿蔔絲', 80, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (92, '小黃瓜絲', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (93, '水果拼盤', '配菜', 0, '素', '生食', '橙', 0, 0, 60, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (93, '季節水果', 600, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (94, '鹽水雞拼盤', '配菜', 0, '雞', '煮', '白', 0, 0, 90, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (94, '雞胸肉', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (95, '燻鮭魚沙拉', '配菜', 0, '魚', '生食', '橙', 0, 0, 100, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (95, '燻鮭魚', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (95, '生菜', 200, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (96, '涼拌海蜇皮', '配菜', 0, '海鮮', '涼拌', '白', 0, 0, 90, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (96, '海蜇皮', 250, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (97, '蔬菜沙拉', '配菜', 0, '素', '生食', '綠', 0, 0, 60, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (97, '綜合生菜', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (98, '酸辣湯', '湯品', 1, '豬', '煮', '紅', 1, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (98, '豬肉絲', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (98, '豆腐', 150, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (98, '黑木耳', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (99, '玉米濃湯', '湯品', 0, '素', '煮', '黃', 0, 1, 35, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (99, '玉米粒', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (99, '玉米醬', 200, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (100, '蘿蔔排骨湯', '湯品', 1, '豬', '煮', '白', 0, 1, 55, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (100, '白蘿蔔', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (100, '排骨', 250, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (101, '味噌豆腐湯', '湯品', 0, '素', '煮', '白', 0, 1, 35, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (101, '豆腐', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (101, '味噌', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (102, '冬瓜蛤蜊湯', '湯品', 0, '海鮮', '煮', '白', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (102, '冬瓜', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (102, '蛤蜊', 200, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (103, '苦瓜排骨湯', '湯品', 1, '豬', '煮', '綠', 0, 0, 50, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (103, '苦瓜', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (103, '排骨', 250, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (104, '竹筍排骨湯', '湯品', 1, '豬', '煮', '白', 0, 0, 50, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (104, '桂竹筍', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (104, '排骨', 250, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (105, '紫菜蛋花湯', '湯品', 0, '蛋', '煮', '黑', 0, 0, 30, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (105, '紫菜', 30, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (105, '雞蛋', 3, '顆');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (106, '紅豆湯圓', '甜點', 0, '素', '煮', '紅', 0, 1, 30, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (106, '紅豆', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (106, '小湯圓', 150, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (107, '布丁', '甜點', 0, '素', '其他', '黃', 0, 1, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (107, '雞蛋布丁', 6, '個');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (108, '涼糕', '甜點', 0, '素', '其他', '白', 0, 0, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (108, '涼糕', 6, '塊');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (109, '芒果青', '甜點', 0, '素', '生食', '橙', 0, 0, 30, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (109, '芒果', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (110, '仙草凍', '甜點', 0, '素', '其他', '黑', 0, 0, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (110, '仙草凍', 500, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (111, '桂圓紅棗茶凍', '甜點', 0, '素', '其他', '褐', 0, 0, 28, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (111, '桂圓', 60, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (111, '紅棗', 40, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (112, '綠豆湯', '甜點', 0, '素', '煮', '綠', 0, 1, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (112, '綠豆', 250, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (113, '銀耳蓮子湯', '甜點', 0, '素', '煮', '白', 0, 1, 30, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (113, '白木耳', 60, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (113, '蓮子', 100, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (114, '古早味紅茶', '飲料', 0, '素', '其他', '褐', 0, 0, 20, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (114, '紅茶', 2000, 'ml');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (115, '冬瓜茶', '飲料', 0, '素', '其他', '褐', 0, 0, 20, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (115, '冬瓜茶磚', 200, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (116, '仙草蜜', '飲料', 0, '素', '其他', '黑', 0, 0, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (116, '仙草凍', 500, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (117, '柳橙汁', '飲料', 0, '素', '其他', '橙', 0, 0, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (117, '柳橙原汁', 1500, 'ml');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (118, '檸檬愛玉', '飲料', 0, '素', '其他', '黃', 0, 0, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (118, '愛玉凍', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (118, '檸檬汁', 100, 'ml');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (119, '梅子綠茶', '飲料', 0, '素', '其他', '綠', 0, 0, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (119, '綠茶', 1800, 'ml');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (119, '梅子醬', 100, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (120, '決明子茶', '飲料', 0, '素', '其他', '褐', 0, 0, 20, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (120, '決明子', 60, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (121, '米漿', '飲料', 0, '素', '其他', '白', 0, 0, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (121, '在來米', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (121, '花生', 60, 'g');
