-- 自動產生，請勿手動編輯。來源：scripts/seedData.js（執行 node scripts/generate-seed-sql.js 重新產生）
DELETE FROM order_menu_items;
DELETE FROM orders;
DELETE FROM monthly_menu_items;
DELETE FROM dish_ingredients;
DELETE FROM dishes;

INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (1, '白飯', '主食', 0, '素', '煮', '白', 0, 0, 20, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (1, '白米', 600, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (2, '炒麵', '主食', 0, '素', '炒', '黃', 0, 0, 35, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (2, '油麵', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (2, '高麗菜', 150, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (2, '紅蘿蔔絲', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (3, '炒米粉', '主食', 0, '素', '炒', '白', 0, 0, 35, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (3, '米粉', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (3, '高麗菜', 150, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (3, '香菇絲', 30, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (4, '筒仔米糕', '主食', 1, '豬', '蒸', '褐', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (4, '長糯米', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (4, '滷肉燥', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (4, '香菇', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (5, '紅燒獅子頭', '主菜', 1, '豬', '滷', '褐', 0, 0, 90, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (5, '豬絞肉', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (5, '大白菜', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (5, '荸薺', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (6, '糖醋排骨', '主菜', 1, '豬', '炸', '紅', 0, 0, 95, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (6, '小排骨', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (6, '鳳梨片', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (6, '青椒', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (7, '客家小炒', '主菜', 1, '豬', '炒', '褐', 0, 0, 85, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (7, '五花肉', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (7, '魷魚乾', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (7, '豆干', 150, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (7, '芹菜', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (8, '香煎雞腿排', '主菜', 0, '雞', '煎', '褐', 0, 0, 100, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (8, '去骨雞腿', 600, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (9, '蔥爆牛肉', '主菜', 0, '牛', '炒', '褐', 0, 0, 120, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (9, '牛肉片', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (9, '青蔥', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (9, '洋蔥', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (10, '樹子蒸鱈魚', '主菜', 0, '魚', '蒸', '白', 0, 0, 150, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (10, '鱈魚', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (10, '破布子', 30, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (10, '薑絲', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (11, '塔香三杯雞', '主菜', 0, '雞', '炒', '褐', 1, 0, 100, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (11, '雞腿肉', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (11, '九層塔', 30, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (11, '老薑', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (12, '避風塘蝦', '主菜', 0, '海鮮', '炸', '黃', 1, 0, 160, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (12, '白蝦', 500, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (12, '蒜酥', 60, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (12, '辣椒末', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (13, '螞蟻上樹', '副菜', 1, '豬', '炒', '紅', 1, 0, 60, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (13, '冬粉', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (13, '豬絞肉', 150, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (14, '麻婆豆腐', '副菜', 1, '豬', '煮', '紅', 1, 0, 55, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (14, '嫩豆腐', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (14, '豬絞肉', 100, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (15, '滷豆干海帶', '副菜', 0, '素', '滷', '褐', 0, 1, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (15, '豆干', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (15, '海帶', 200, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (16, '涼拌小黃瓜', '副菜', 0, '素', '涼拌', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (16, '小黃瓜', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (16, '蒜末', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (17, '蒜泥白肉', '副菜', 1, '豬', '煮', '白', 0, 0, 70, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (17, '五花肉片', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (17, '蒜泥', 30, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (18, '蔭豉蚵仔', '副菜', 0, '海鮮', '煮', '黑', 0, 0, 90, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (18, '鮮蚵', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (18, '豆豉', 20, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (18, '薑絲', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (19, '涼拌木耳', '副菜', 0, '素', '涼拌', '黑', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (19, '黑木耳', 250, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (20, '客家封肉', '副菜', 1, '豬', '滷', '褐', 0, 1, 85, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (20, '五花肉塊', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (20, '梅乾菜', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (21, '清炒高麗菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (21, '高麗菜', 500, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (22, '炒地瓜葉', '時蔬', 0, '素', '炒', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (22, '地瓜葉', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (23, '蒜炒A菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 40, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (23, 'A菜', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (24, '香菇燴時蔬', '時蔬', 0, '素', '煮', '綠', 0, 1, 50, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (24, '綜合時蔬', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (24, '乾香菇', 30, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (25, '塔香茄子', '時蔬', 0, '素', '炒', '紫', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (25, '茄子', 400, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (25, '九層塔', 20, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (26, '炒青花菜', '時蔬', 0, '素', '炒', '綠', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (26, '青花菜', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (27, '五味小卷拼盤', '配菜', 0, '海鮮', '涼拌', '白', 0, 0, 100, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (27, '小卷', 300, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (28, '滷味拼盤', '配菜', 1, '豬', '滷', '褐', 0, 0, 90, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (28, '豬耳朵', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (28, '豆干', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (28, '海帶', 100, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (29, '涼拌三絲', '配菜', 0, '素', '涼拌', '白', 0, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (29, '干絲', 150, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (29, '紅蘿蔔絲', 80, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (29, '小黃瓜絲', 80, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (30, '水果拼盤', '配菜', 0, '素', '生食', '橙', 0, 0, 60, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (30, '季節水果', 600, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (31, '酸辣湯', '湯品', 1, '豬', '煮', '紅', 1, 0, 45, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (31, '豬肉絲', 100, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (31, '豆腐', 150, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (31, '黑木耳', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (32, '玉米濃湯', '湯品', 0, '素', '煮', '黃', 0, 1, 35, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (32, '玉米粒', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (32, '玉米醬', 200, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (33, '蘿蔔排骨湯', '湯品', 1, '豬', '煮', '白', 0, 1, 55, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (33, '白蘿蔔', 300, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (33, '排骨', 250, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (34, '味噌豆腐湯', '湯品', 0, '素', '煮', '白', 0, 1, 35, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (34, '豆腐', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (34, '味噌', 50, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (35, '紅豆湯圓', '甜點', 0, '素', '煮', '紅', 0, 1, 30, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (35, '紅豆', 200, 'g');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (35, '小湯圓', 150, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (36, '布丁', '甜點', 0, '素', '其他', '黃', 0, 1, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (36, '雞蛋布丁', 6, '個');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (37, '涼糕', '甜點', 0, '素', '其他', '白', 0, 0, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (37, '涼糕', 6, '塊');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (38, '芒果青', '甜點', 0, '素', '生食', '橙', 0, 0, 30, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (38, '芒果', 400, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (39, '古早味紅茶', '飲料', 0, '素', '其他', '褐', 0, 0, 20, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (39, '紅茶', 2000, 'ml');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (40, '冬瓜茶', '飲料', 0, '素', '其他', '褐', 0, 0, 20, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (40, '冬瓜茶磚', 200, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (41, '仙草蜜', '飲料', 0, '素', '其他', '黑', 0, 0, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (41, '仙草凍', 500, 'g');
INSERT INTO dishes (id, name, category, is_pork, protein_type, cooking_method, color_tag, is_spicy, is_soft, price, notes) VALUES (42, '柳橙汁', '飲料', 0, '素', '其他', '橙', 0, 0, 25, '');
INSERT INTO dish_ingredients (dish_id, name, qty, unit) VALUES (42, '柳橙原汁', 1500, 'ml');

INSERT INTO monthly_menu_items (month, slot_category, variant, dish_id, sort_order) VALUES ('2026-09', '主菜', '一般', 5, 1);
INSERT INTO monthly_menu_items (month, slot_category, variant, dish_id, sort_order) VALUES ('2026-09', '主菜', '不豬', 8, 1);
INSERT INTO monthly_menu_items (month, slot_category, variant, dish_id, sort_order) VALUES ('2026-09', '主菜', '一般', 6, 2);
INSERT INTO monthly_menu_items (month, slot_category, variant, dish_id, sort_order) VALUES ('2026-09', '主菜', '不豬', 10, 2);
INSERT INTO monthly_menu_items (month, slot_category, variant, dish_id, sort_order) VALUES ('2026-09', '副菜', '一般', 15, 1);
INSERT INTO monthly_menu_items (month, slot_category, variant, dish_id, sort_order) VALUES ('2026-09', '副菜', '一般', 16, 2);
INSERT INTO monthly_menu_items (month, slot_category, variant, dish_id, sort_order) VALUES ('2026-09', '時蔬', '一般', 21, 1);
INSERT INTO monthly_menu_items (month, slot_category, variant, dish_id, sort_order) VALUES ('2026-09', '時蔬', '一般', 22, 2);
