// 範例菜色資料庫（僅供系統初次啟動示範使用，之後可在「菜色資料庫」頁面自行新增/修改/刪除）
// ingredients 為主要食材，不含調味料；qty 為「每桌（每一份訂購數量）」用量
// 這份資料是 migrations/0002_seed.sql 的來源，修改後請重新執行：
//   node scripts/generate-seed-sql.js
//
// 主菜/副菜/時蔬刻意擴充到較大的數量，是為了讓「月菜單管理」的自動排月曆功能
// （每天2主菜+2副菜+2時蔬，共30天）有足夠的菜色可以輪替、避免同一道菜在一個月內
// 太快重複出現。
const DISHES = [
  // ==================== 主食 ====================
  { name: '白飯', category: '主食', protein_type: '素', cooking_method: '煮', color_tag: '白', price: 20,
    ingredients: [{ name: '白米', qty: 600, unit: 'g' }] },
  { name: '炒麵', category: '主食', protein_type: '素', cooking_method: '炒', color_tag: '黃', price: 35,
    ingredients: [{ name: '油麵', qty: 500, unit: 'g' }, { name: '高麗菜', qty: 150, unit: 'g' }, { name: '紅蘿蔔絲', qty: 50, unit: 'g' }] },
  { name: '炒米粉', category: '主食', protein_type: '素', cooking_method: '炒', color_tag: '白', price: 35,
    ingredients: [{ name: '米粉', qty: 400, unit: 'g' }, { name: '高麗菜', qty: 150, unit: 'g' }, { name: '香菇絲', qty: 30, unit: 'g' }] },
  { name: '筒仔米糕', category: '主食', protein_type: '豬', cooking_method: '蒸', color_tag: '褐', price: 40, is_pork: 1,
    ingredients: [{ name: '長糯米', qty: 500, unit: 'g' }, { name: '滷肉燥', qty: 100, unit: 'g' }, { name: '香菇', qty: 20, unit: 'g' }] },
  { name: '芋頭米粉', category: '主食', protein_type: '素', cooking_method: '炒', color_tag: '褐', price: 40,
    ingredients: [{ name: '米粉', qty: 400, unit: 'g' }, { name: '芋頭', qty: 150, unit: 'g' }] },
  { name: '蛋炒飯', category: '主食', protein_type: '蛋', cooking_method: '炒', color_tag: '黃', price: 35,
    ingredients: [{ name: '白飯', qty: 600, unit: 'g' }, { name: '雞蛋', qty: 3, unit: '顆' }] },
  { name: '油飯', category: '主食', protein_type: '豬', cooking_method: '蒸', color_tag: '褐', price: 45, is_pork: 1,
    ingredients: [{ name: '長糯米', qty: 500, unit: 'g' }, { name: '豬肉絲', qty: 100, unit: 'g' }, { name: '香菇', qty: 20, unit: 'g' }] },
  { name: '什錦炒飯', category: '主食', protein_type: '素', cooking_method: '炒', color_tag: '黃', price: 40,
    ingredients: [{ name: '白飯', qty: 600, unit: 'g' }, { name: '玉米粒', qty: 80, unit: 'g' }, { name: '青豆', qty: 50, unit: 'g' }] },

  // ==================== 主菜 ====================
  { name: '紅燒獅子頭', category: '主菜', protein_type: '豬', cooking_method: '滷', color_tag: '褐', price: 90, is_pork: 1,
    ingredients: [{ name: '豬絞肉', qty: 500, unit: 'g' }, { name: '大白菜', qty: 300, unit: 'g' }, { name: '荸薺', qty: 80, unit: 'g' }] },
  { name: '糖醋排骨', category: '主菜', protein_type: '豬', cooking_method: '炸', color_tag: '紅', price: 95, is_pork: 1,
    ingredients: [{ name: '小排骨', qty: 500, unit: 'g' }, { name: '鳳梨片', qty: 100, unit: 'g' }, { name: '青椒', qty: 50, unit: 'g' }] },
  { name: '客家小炒', category: '主菜', protein_type: '豬', cooking_method: '炒', color_tag: '褐', price: 85, is_pork: 1,
    ingredients: [{ name: '五花肉', qty: 300, unit: 'g' }, { name: '魷魚乾', qty: 100, unit: 'g' }, { name: '豆干', qty: 150, unit: 'g' }, { name: '芹菜', qty: 80, unit: 'g' }] },
  { name: '香煎雞腿排', category: '主菜', protein_type: '雞', cooking_method: '煎', color_tag: '褐', price: 100,
    ingredients: [{ name: '去骨雞腿', qty: 600, unit: 'g' }] },
  { name: '蔥爆牛肉', category: '主菜', protein_type: '牛', cooking_method: '炒', color_tag: '褐', price: 120,
    ingredients: [{ name: '牛肉片', qty: 400, unit: 'g' }, { name: '青蔥', qty: 100, unit: 'g' }, { name: '洋蔥', qty: 80, unit: 'g' }] },
  { name: '樹子蒸鱈魚', category: '主菜', protein_type: '魚', cooking_method: '蒸', color_tag: '白', price: 150,
    ingredients: [{ name: '鱈魚', qty: 500, unit: 'g' }, { name: '破布子', qty: 30, unit: 'g' }, { name: '薑絲', qty: 20, unit: 'g' }] },
  { name: '塔香三杯雞', category: '主菜', protein_type: '雞', cooking_method: '炒', color_tag: '褐', price: 100, is_spicy: 1,
    ingredients: [{ name: '雞腿肉', qty: 500, unit: 'g' }, { name: '九層塔', qty: 30, unit: 'g' }, { name: '老薑', qty: 50, unit: 'g' }] },
  { name: '避風塘蝦', category: '主菜', protein_type: '海鮮', cooking_method: '炸', color_tag: '黃', price: 160, is_spicy: 1,
    ingredients: [{ name: '白蝦', qty: 500, unit: 'g' }, { name: '蒜酥', qty: 60, unit: 'g' }, { name: '辣椒末', qty: 20, unit: 'g' }] },
  { name: '蒜泥蒸魚', category: '主菜', protein_type: '魚', cooking_method: '蒸', color_tag: '白', price: 120,
    ingredients: [{ name: '鱸魚', qty: 500, unit: 'g' }, { name: '蒜泥', qty: 40, unit: 'g' }] },
  { name: '京都排骨', category: '主菜', protein_type: '豬', cooking_method: '炸', color_tag: '紅', price: 90, is_pork: 1,
    ingredients: [{ name: '大排', qty: 500, unit: 'g' }, { name: '洋蔥', qty: 60, unit: 'g' }] },
  { name: '東坡肉', category: '主菜', protein_type: '豬', cooking_method: '滷', color_tag: '褐', price: 110, is_pork: 1, is_soft: 1,
    ingredients: [{ name: '五花肉塊', qty: 500, unit: 'g' }] },
  { name: '左宗棠雞', category: '主菜', protein_type: '雞', cooking_method: '炸', color_tag: '紅', price: 110, is_spicy: 1,
    ingredients: [{ name: '雞胸肉', qty: 500, unit: 'g' }, { name: '乾辣椒', qty: 20, unit: 'g' }] },
  { name: '宮保雞丁', category: '主菜', protein_type: '雞', cooking_method: '炒', color_tag: '紅', price: 95, is_spicy: 1,
    ingredients: [{ name: '雞胸肉', qty: 400, unit: 'g' }, { name: '花生', qty: 80, unit: 'g' }, { name: '乾辣椒', qty: 15, unit: 'g' }] },
  { name: '蜜汁叉燒', category: '主菜', protein_type: '豬', cooking_method: '烤', color_tag: '紅', price: 100, is_pork: 1,
    ingredients: [{ name: '梅花肉', qty: 500, unit: 'g' }] },
  { name: '檸檬蒸魚', category: '主菜', protein_type: '魚', cooking_method: '蒸', color_tag: '白', price: 130,
    ingredients: [{ name: '龍膽石斑', qty: 500, unit: 'g' }, { name: '檸檬', qty: 2, unit: '顆' }] },
  { name: '紅燒牛腩', category: '主菜', protein_type: '牛', cooking_method: '滷', color_tag: '褐', price: 140, is_soft: 1,
    ingredients: [{ name: '牛腩', qty: 500, unit: 'g' }, { name: '紅蘿蔔', qty: 100, unit: 'g' }] },
  { name: '黑胡椒牛柳', category: '主菜', protein_type: '牛', cooking_method: '炒', color_tag: '褐', price: 130,
    ingredients: [{ name: '牛柳', qty: 400, unit: 'g' }, { name: '洋蔥', qty: 80, unit: 'g' }] },
  { name: '塔香海鮮', category: '主菜', protein_type: '海鮮', cooking_method: '炒', color_tag: '黃', price: 150, is_spicy: 1,
    ingredients: [{ name: '綜合海鮮', qty: 400, unit: 'g' }, { name: '九層塔', qty: 20, unit: 'g' }] },
  { name: '白斬雞', category: '主菜', protein_type: '雞', cooking_method: '煮', color_tag: '白', price: 100,
    ingredients: [{ name: '土雞腿', qty: 600, unit: 'g' }] },
  { name: '燒酒雞', category: '主菜', protein_type: '雞', cooking_method: '滷', color_tag: '褐', price: 110,
    ingredients: [{ name: '雞腿肉', qty: 500, unit: 'g' }, { name: '米酒', qty: 300, unit: 'ml' }] },
  { name: '蒜香排骨酥', category: '主菜', protein_type: '豬', cooking_method: '炸', color_tag: '褐', price: 95, is_pork: 1,
    ingredients: [{ name: '小排骨', qty: 500, unit: 'g' }, { name: '蒜末', qty: 40, unit: 'g' }] },
  { name: '沙茶羊肉', category: '主菜', protein_type: '羊', cooking_method: '炒', color_tag: '褐', price: 150, is_spicy: 1,
    ingredients: [{ name: '羊肉片', qty: 400, unit: 'g' }, { name: '沙茶醬', qty: 50, unit: 'g' } ] },
  { name: 'XO醬炒海鮮', category: '主菜', protein_type: '海鮮', cooking_method: '炒', color_tag: '紅', price: 160, is_spicy: 1,
    ingredients: [{ name: '綜合海鮮', qty: 400, unit: 'g' }, { name: 'XO醬', qty: 40, unit: 'g' }] },
  { name: '蒸烤鴨腿', category: '主菜', protein_type: '其他', cooking_method: '烤', color_tag: '褐', price: 140,
    ingredients: [{ name: '鴨腿', qty: 500, unit: 'g' }] },
  { name: '檸檬鮭魚', category: '主菜', protein_type: '魚', cooking_method: '煎', color_tag: '橙', price: 140,
    ingredients: [{ name: '鮭魚', qty: 450, unit: 'g' }, { name: '檸檬', qty: 1, unit: '顆' }] },
  { name: '蔥燒鯽魚', category: '主菜', protein_type: '魚', cooking_method: '煎', color_tag: '褐', price: 110,
    ingredients: [{ name: '鯽魚', qty: 500, unit: 'g' }, { name: '青蔥', qty: 60, unit: 'g' }] },
  { name: '塔香烘蛋', category: '主菜', protein_type: '蛋', cooking_method: '煎', color_tag: '黃', price: 70,
    ingredients: [{ name: '雞蛋', qty: 6, unit: '顆' }, { name: '九層塔', qty: 20, unit: 'g' }] },
  { name: '蒜燒中卷', category: '主菜', protein_type: '海鮮', cooking_method: '炒', color_tag: '白', price: 120,
    ingredients: [{ name: '中卷', qty: 400, unit: 'g' }, { name: '蒜苗', qty: 60, unit: 'g' }] },
  { name: '紅麴排骨', category: '主菜', protein_type: '豬', cooking_method: '炸', color_tag: '紅', price: 95, is_pork: 1,
    ingredients: [{ name: '小排骨', qty: 500, unit: 'g' }, { name: '紅麴醬', qty: 40, unit: 'g' }] },
  { name: '蜜汁烤雞腿', category: '主菜', protein_type: '雞', cooking_method: '烤', color_tag: '褐', price: 110,
    ingredients: [{ name: '雞腿', qty: 600, unit: 'g' }] },
  { name: '塔香牛肉', category: '主菜', protein_type: '牛', cooking_method: '炒', color_tag: '褐', price: 140, is_spicy: 1,
    ingredients: [{ name: '牛肉片', qty: 400, unit: 'g' }, { name: '九層塔', qty: 20, unit: 'g' }] },
  { name: '荷葉粉蒸肉', category: '主菜', protein_type: '豬', cooking_method: '蒸', color_tag: '褐', price: 100, is_pork: 1, is_soft: 1,
    ingredients: [{ name: '五花肉片', qty: 400, unit: 'g' }, { name: '蒸肉粉', qty: 80, unit: 'g' }] },
  { name: '檸檬雞排', category: '主菜', protein_type: '雞', cooking_method: '炸', color_tag: '黃', price: 100,
    ingredients: [{ name: '雞胸肉', qty: 500, unit: 'g' }, { name: '檸檬', qty: 2, unit: '顆' }] },
  { name: '麻油雞', category: '主菜', protein_type: '雞', cooking_method: '煮', color_tag: '褐', price: 110, is_soft: 1,
    ingredients: [{ name: '雞腿肉', qty: 500, unit: 'g' }, { name: '麻油', qty: 50, unit: 'ml' }, { name: '老薑', qty: 40, unit: 'g' }] },
  { name: '蒜蓉蒸蝦', category: '主菜', protein_type: '海鮮', cooking_method: '蒸', color_tag: '白', price: 150,
    ingredients: [{ name: '草蝦', qty: 500, unit: 'g' }, { name: '蒜蓉', qty: 50, unit: 'g' }] },

  // ==================== 副菜 ====================
  { name: '螞蟻上樹', category: '副菜', protein_type: '豬', cooking_method: '炒', color_tag: '紅', price: 60, is_pork: 1, is_spicy: 1,
    ingredients: [{ name: '冬粉', qty: 200, unit: 'g' }, { name: '豬絞肉', qty: 150, unit: 'g' }] },
  { name: '麻婆豆腐', category: '副菜', protein_type: '豬', cooking_method: '煮', color_tag: '紅', price: 55, is_pork: 1, is_spicy: 1,
    ingredients: [{ name: '嫩豆腐', qty: 400, unit: 'g' }, { name: '豬絞肉', qty: 100, unit: 'g' }] },
  { name: '滷豆干海帶', category: '副菜', protein_type: '素', cooking_method: '滷', color_tag: '褐', price: 45, is_soft: 1,
    ingredients: [{ name: '豆干', qty: 200, unit: 'g' }, { name: '海帶', qty: 200, unit: 'g' }] },
  { name: '涼拌小黃瓜', category: '副菜', protein_type: '素', cooking_method: '涼拌', color_tag: '綠', price: 40,
    ingredients: [{ name: '小黃瓜', qty: 300, unit: 'g' }, { name: '蒜末', qty: 20, unit: 'g' }] },
  { name: '蒜泥白肉', category: '副菜', protein_type: '豬', cooking_method: '煮', color_tag: '白', price: 70, is_pork: 1,
    ingredients: [{ name: '五花肉片', qty: 300, unit: 'g' }, { name: '蒜泥', qty: 30, unit: 'g' }] },
  { name: '蔭豉蚵仔', category: '副菜', protein_type: '海鮮', cooking_method: '煮', color_tag: '黑', price: 90,
    ingredients: [{ name: '鮮蚵', qty: 300, unit: 'g' }, { name: '豆豉', qty: 20, unit: 'g' }, { name: '薑絲', qty: 20, unit: 'g' }] },
  { name: '涼拌木耳', category: '副菜', protein_type: '素', cooking_method: '涼拌', color_tag: '黑', price: 40,
    ingredients: [{ name: '黑木耳', qty: 250, unit: 'g' }] },
  { name: '客家封肉', category: '副菜', protein_type: '豬', cooking_method: '滷', color_tag: '褐', price: 85, is_pork: 1, is_soft: 1,
    ingredients: [{ name: '五花肉塊', qty: 400, unit: 'g' }, { name: '梅乾菜', qty: 80, unit: 'g' }] },
  { name: '塔香豆腐煲', category: '副菜', protein_type: '素', cooking_method: '滷', color_tag: '褐', price: 55,
    ingredients: [{ name: '板豆腐', qty: 400, unit: 'g' }, { name: '九層塔', qty: 15, unit: 'g' }] },
  { name: '開陽白菜', category: '副菜', protein_type: '素', cooking_method: '煮', color_tag: '白', price: 45,
    ingredients: [{ name: '大白菜', qty: 400, unit: 'g' }, { name: '蝦米', qty: 20, unit: 'g' }] },
  { name: '涼拌豆芽', category: '副菜', protein_type: '素', cooking_method: '涼拌', color_tag: '白', price: 35,
    ingredients: [{ name: '綠豆芽', qty: 350, unit: 'g' }] },
  { name: '紅燒杏鮑菇', category: '副菜', protein_type: '素', cooking_method: '滷', color_tag: '褐', price: 50,
    ingredients: [{ name: '杏鮑菇', qty: 300, unit: 'g' }] },
  { name: '皮蛋豆腐', category: '副菜', protein_type: '蛋', cooking_method: '生食', color_tag: '黑', price: 40,
    ingredients: [{ name: '皮蛋', qty: 4, unit: '顆' }, { name: '嫩豆腐', qty: 300, unit: 'g' }] },
  { name: '涼拌海帶芽', category: '副菜', protein_type: '素', cooking_method: '涼拌', color_tag: '綠', price: 35,
    ingredients: [{ name: '海帶芽', qty: 200, unit: 'g' }] },
  { name: '紹興醉雞', category: '副菜', protein_type: '雞', cooking_method: '煮', color_tag: '白', price: 80,
    ingredients: [{ name: '去骨雞腿', qty: 400, unit: 'g' }, { name: '紹興酒', qty: 100, unit: 'ml' }] },
  { name: '五香滷牛腱', category: '副菜', protein_type: '牛', cooking_method: '滷', color_tag: '褐', price: 90,
    ingredients: [{ name: '牛腱', qty: 400, unit: 'g' }] },
  { name: '涼拌花枝', category: '副菜', protein_type: '海鮮', cooking_method: '涼拌', color_tag: '白', price: 70,
    ingredients: [{ name: '花枝', qty: 300, unit: 'g' }] },
  { name: '客家炒肉絲', category: '副菜', protein_type: '豬', cooking_method: '炒', color_tag: '褐', price: 60, is_pork: 1,
    ingredients: [{ name: '豬肉絲', qty: 250, unit: 'g' }, { name: '豆干絲', qty: 100, unit: 'g' }] },
  { name: '塔香茭白筍', category: '副菜', protein_type: '素', cooking_method: '炒', color_tag: '白', price: 45,
    ingredients: [{ name: '茭白筍', qty: 300, unit: 'g' }, { name: '九層塔', qty: 15, unit: 'g' }] },
  { name: '破布子蒸肉餅', category: '副菜', protein_type: '豬', cooking_method: '蒸', color_tag: '褐', price: 65, is_pork: 1, is_soft: 1,
    ingredients: [{ name: '豬絞肉', qty: 300, unit: 'g' }, { name: '破布子', qty: 30, unit: 'g' }] },
  { name: '涼拌娃娃菜', category: '副菜', protein_type: '素', cooking_method: '涼拌', color_tag: '綠', price: 40,
    ingredients: [{ name: '娃娃菜', qty: 300, unit: 'g' }] },
  { name: '蒜香四季豆', category: '副菜', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 45,
    ingredients: [{ name: '四季豆', qty: 300, unit: 'g' }, { name: '蒜末', qty: 20, unit: 'g' }] },
  { name: '客家小魚乾', category: '副菜', protein_type: '海鮮', cooking_method: '炒', color_tag: '黑', price: 55, is_spicy: 1,
    ingredients: [{ name: '小魚乾', qty: 150, unit: 'g' }, { name: '花生', qty: 80, unit: 'g' }] },
  { name: '塔香皮蛋', category: '副菜', protein_type: '蛋', cooking_method: '炒', color_tag: '黑', price: 45,
    ingredients: [{ name: '皮蛋', qty: 4, unit: '顆' }, { name: '九層塔', qty: 15, unit: 'g' }] },
  { name: '涼拌牛腱', category: '副菜', protein_type: '牛', cooking_method: '涼拌', color_tag: '褐', price: 85,
    ingredients: [{ name: '牛腱', qty: 350, unit: 'g' }] },
  { name: '塔香素肚', category: '副菜', protein_type: '素', cooking_method: '炒', color_tag: '黃', price: 45,
    ingredients: [{ name: '素肚', qty: 250, unit: 'g' }, { name: '九層塔', qty: 15, unit: 'g' }] },

  // ==================== 時蔬 ====================
  { name: '清炒高麗菜', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 40,
    ingredients: [{ name: '高麗菜', qty: 500, unit: 'g' }] },
  { name: '炒地瓜葉', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 40,
    ingredients: [{ name: '地瓜葉', qty: 400, unit: 'g' }] },
  { name: '蒜炒A菜', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 40,
    ingredients: [{ name: 'A菜', qty: 400, unit: 'g' }] },
  { name: '香菇燴時蔬', category: '時蔬', protein_type: '素', cooking_method: '煮', color_tag: '綠', price: 50, is_soft: 1,
    ingredients: [{ name: '綜合時蔬', qty: 400, unit: 'g' }, { name: '乾香菇', qty: 30, unit: 'g' }] },
  { name: '塔香茄子', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '紫', price: 45,
    ingredients: [{ name: '茄子', qty: 400, unit: 'g' }, { name: '九層塔', qty: 20, unit: 'g' }] },
  { name: '炒青花菜', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 45,
    ingredients: [{ name: '青花菜', qty: 400, unit: 'g' }] },
  { name: '開陽高麗菜', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 45,
    ingredients: [{ name: '高麗菜', qty: 450, unit: 'g' }, { name: '蝦米', qty: 15, unit: 'g' }] },
  { name: '蒜炒山蘇', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 50,
    ingredients: [{ name: '山蘇', qty: 350, unit: 'g' }] },
  { name: '皇宮菜', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 45,
    ingredients: [{ name: '皇宮菜', qty: 400, unit: 'g' }] },
  { name: '炒龍鬚菜', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 50,
    ingredients: [{ name: '龍鬚菜', qty: 350, unit: 'g' }] },
  { name: '蒜炒油菜', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 40,
    ingredients: [{ name: '油菜', qty: 400, unit: 'g' }] },
  { name: '清炒絲瓜', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 45,
    ingredients: [{ name: '絲瓜', qty: 400, unit: 'g' }] },
  { name: '炒山藥', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '白', price: 50,
    ingredients: [{ name: '山藥', qty: 350, unit: 'g' }] },
  { name: '涼拌秋葵', category: '時蔬', protein_type: '素', cooking_method: '涼拌', color_tag: '綠', price: 40,
    ingredients: [{ name: '秋葵', qty: 300, unit: 'g' }] },
  { name: '塔香四季豆', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 45,
    ingredients: [{ name: '四季豆', qty: 300, unit: 'g' }, { name: '九層塔', qty: 15, unit: 'g' }] },
  { name: '清炒白花椰', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '白', price: 45,
    ingredients: [{ name: '白花椰菜', qty: 400, unit: 'g' }] },
  { name: '蒜香蘆筍', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 55,
    ingredients: [{ name: '蘆筍', qty: 300, unit: 'g' }, { name: '蒜末', qty: 20, unit: 'g' }] },
  { name: '炒紅鳳菜', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '紅', price: 45,
    ingredients: [{ name: '紅鳳菜', qty: 350, unit: 'g' }] },
  { name: '蒜炒莧菜', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 45,
    ingredients: [{ name: '莧菜', qty: 350, unit: 'g' }] },
  { name: '蒜炒空心菜', category: '時蔬', protein_type: '素', cooking_method: '炒', color_tag: '綠', price: 40,
    ingredients: [{ name: '空心菜', qty: 400, unit: 'g' }] },

  // ==================== 配菜（拼盤） ====================
  { name: '五味小卷拼盤', category: '配菜', protein_type: '海鮮', cooking_method: '涼拌', color_tag: '白', price: 100,
    ingredients: [{ name: '小卷', qty: 300, unit: 'g' }] },
  { name: '滷味拼盤', category: '配菜', protein_type: '豬', cooking_method: '滷', color_tag: '褐', price: 90, is_pork: 1,
    ingredients: [{ name: '豬耳朵', qty: 100, unit: 'g' }, { name: '豆干', qty: 100, unit: 'g' }, { name: '海帶', qty: 100, unit: 'g' }] },
  { name: '涼拌三絲', category: '配菜', protein_type: '素', cooking_method: '涼拌', color_tag: '白', price: 45,
    ingredients: [{ name: '干絲', qty: 150, unit: 'g' }, { name: '紅蘿蔔絲', qty: 80, unit: 'g' }, { name: '小黃瓜絲', qty: 80, unit: 'g' }] },
  { name: '水果拼盤', category: '配菜', protein_type: '素', cooking_method: '生食', color_tag: '橙', price: 60,
    ingredients: [{ name: '季節水果', qty: 600, unit: 'g' }] },
  { name: '鹽水雞拼盤', category: '配菜', protein_type: '雞', cooking_method: '煮', color_tag: '白', price: 90,
    ingredients: [{ name: '雞胸肉', qty: 400, unit: 'g' }] },
  { name: '燻鮭魚沙拉', category: '配菜', protein_type: '魚', cooking_method: '生食', color_tag: '橙', price: 100,
    ingredients: [{ name: '燻鮭魚', qty: 200, unit: 'g' }, { name: '生菜', qty: 200, unit: 'g' }] },
  { name: '涼拌海蜇皮', category: '配菜', protein_type: '海鮮', cooking_method: '涼拌', color_tag: '白', price: 90,
    ingredients: [{ name: '海蜇皮', qty: 250, unit: 'g' }] },
  { name: '蔬菜沙拉', category: '配菜', protein_type: '素', cooking_method: '生食', color_tag: '綠', price: 60,
    ingredients: [{ name: '綜合生菜', qty: 400, unit: 'g' }] },

  // ==================== 湯品 ====================
  { name: '酸辣湯', category: '湯品', protein_type: '豬', cooking_method: '煮', color_tag: '紅', price: 45, is_pork: 1, is_spicy: 1,
    ingredients: [{ name: '豬肉絲', qty: 100, unit: 'g' }, { name: '豆腐', qty: 150, unit: 'g' }, { name: '黑木耳', qty: 50, unit: 'g' }] },
  { name: '玉米濃湯', category: '湯品', protein_type: '素', cooking_method: '煮', color_tag: '黃', price: 35, is_soft: 1,
    ingredients: [{ name: '玉米粒', qty: 200, unit: 'g' }, { name: '玉米醬', qty: 200, unit: 'g' }] },
  { name: '蘿蔔排骨湯', category: '湯品', protein_type: '豬', cooking_method: '煮', color_tag: '白', price: 55, is_pork: 1, is_soft: 1,
    ingredients: [{ name: '白蘿蔔', qty: 300, unit: 'g' }, { name: '排骨', qty: 250, unit: 'g' }] },
  { name: '味噌豆腐湯', category: '湯品', protein_type: '素', cooking_method: '煮', color_tag: '白', price: 35, is_soft: 1,
    ingredients: [{ name: '豆腐', qty: 200, unit: 'g' }, { name: '味噌', qty: 50, unit: 'g' }] },
  { name: '冬瓜蛤蜊湯', category: '湯品', protein_type: '海鮮', cooking_method: '煮', color_tag: '白', price: 45,
    ingredients: [{ name: '冬瓜', qty: 300, unit: 'g' }, { name: '蛤蜊', qty: 200, unit: 'g' }] },
  { name: '苦瓜排骨湯', category: '湯品', protein_type: '豬', cooking_method: '煮', color_tag: '綠', price: 50, is_pork: 1,
    ingredients: [{ name: '苦瓜', qty: 300, unit: 'g' }, { name: '排骨', qty: 250, unit: 'g' }] },
  { name: '竹筍排骨湯', category: '湯品', protein_type: '豬', cooking_method: '煮', color_tag: '白', price: 50, is_pork: 1,
    ingredients: [{ name: '桂竹筍', qty: 300, unit: 'g' }, { name: '排骨', qty: 250, unit: 'g' }] },
  { name: '紫菜蛋花湯', category: '湯品', protein_type: '蛋', cooking_method: '煮', color_tag: '黑', price: 30,
    ingredients: [{ name: '紫菜', qty: 30, unit: 'g' }, { name: '雞蛋', qty: 3, unit: '顆' }] },

  // ==================== 甜點 ====================
  { name: '紅豆湯圓', category: '甜點', protein_type: '素', cooking_method: '煮', color_tag: '紅', price: 30, is_soft: 1,
    ingredients: [{ name: '紅豆', qty: 200, unit: 'g' }, { name: '小湯圓', qty: 150, unit: 'g' }] },
  { name: '布丁', category: '甜點', protein_type: '素', cooking_method: '其他', color_tag: '黃', price: 25, is_soft: 1,
    ingredients: [{ name: '雞蛋布丁', qty: 6, unit: '個' }] },
  { name: '涼糕', category: '甜點', protein_type: '素', cooking_method: '其他', color_tag: '白', price: 25,
    ingredients: [{ name: '涼糕', qty: 6, unit: '塊' }] },
  { name: '芒果青', category: '甜點', protein_type: '素', cooking_method: '生食', color_tag: '橙', price: 30,
    ingredients: [{ name: '芒果', qty: 400, unit: 'g' }] },
  { name: '仙草凍', category: '甜點', protein_type: '素', cooking_method: '其他', color_tag: '黑', price: 25,
    ingredients: [{ name: '仙草凍', qty: 500, unit: 'g' }] },
  { name: '桂圓紅棗茶凍', category: '甜點', protein_type: '素', cooking_method: '其他', color_tag: '褐', price: 28,
    ingredients: [{ name: '桂圓', qty: 60, unit: 'g' }, { name: '紅棗', qty: 40, unit: 'g' }] },
  { name: '綠豆湯', category: '甜點', protein_type: '素', cooking_method: '煮', color_tag: '綠', price: 25, is_soft: 1,
    ingredients: [{ name: '綠豆', qty: 250, unit: 'g' }] },
  { name: '銀耳蓮子湯', category: '甜點', protein_type: '素', cooking_method: '煮', color_tag: '白', price: 30, is_soft: 1,
    ingredients: [{ name: '白木耳', qty: 60, unit: 'g' }, { name: '蓮子', qty: 100, unit: 'g' }] },

  // ==================== 飲料 ====================
  { name: '古早味紅茶', category: '飲料', protein_type: '素', cooking_method: '其他', color_tag: '褐', price: 20,
    ingredients: [{ name: '紅茶', qty: 2000, unit: 'ml' }] },
  { name: '冬瓜茶', category: '飲料', protein_type: '素', cooking_method: '其他', color_tag: '褐', price: 20,
    ingredients: [{ name: '冬瓜茶磚', qty: 200, unit: 'g' }] },
  { name: '仙草蜜', category: '飲料', protein_type: '素', cooking_method: '其他', color_tag: '黑', price: 25,
    ingredients: [{ name: '仙草凍', qty: 500, unit: 'g' }] },
  { name: '柳橙汁', category: '飲料', protein_type: '素', cooking_method: '其他', color_tag: '橙', price: 25,
    ingredients: [{ name: '柳橙原汁', qty: 1500, unit: 'ml' }] },
  { name: '檸檬愛玉', category: '飲料', protein_type: '素', cooking_method: '其他', color_tag: '黃', price: 25,
    ingredients: [{ name: '愛玉凍', qty: 500, unit: 'g' }, { name: '檸檬汁', qty: 100, unit: 'ml' }] },
  { name: '梅子綠茶', category: '飲料', protein_type: '素', cooking_method: '其他', color_tag: '綠', price: 25,
    ingredients: [{ name: '綠茶', qty: 1800, unit: 'ml' }, { name: '梅子醬', qty: 100, unit: 'g' }] },
  { name: '決明子茶', category: '飲料', protein_type: '素', cooking_method: '其他', color_tag: '褐', price: 20,
    ingredients: [{ name: '決明子', qty: 60, unit: 'g' }] },
  { name: '米漿', category: '飲料', protein_type: '素', cooking_method: '其他', color_tag: '白', price: 25,
    ingredients: [{ name: '在來米', qty: 200, unit: 'g' }, { name: '花生', qty: 60, unit: 'g' }] },
];

module.exports = { DISHES };
